name: Test

on:
  push:
    branches:
    - 'playwright'

jobs:
  ci-current:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        shopware-version:
#          - 'v6.4.1' # Error 500
#          - 'v6.4.2' # Error 500
          - 'v6.4.3'
#          - 'v6.4.4'
#          - 'v6.4.5'
#          - 'v6.4.6'
#          - 'v6.4.7'
#          - 'v6.4.8'
#          - 'v6.4.9'
#          - 'v6.4.10'
#          - 'v6.4.11'
#          - 'v6.4.12'
#          - 'v6.4.13'
#          - 'v6.4.14'
#          - 'v6.4.15'
#          - 'v6.4.16'
#          - 'v6.4.17'
#          - 'v6.4.18'
#          - 'v6.4.19'
#          - 'v6.4.20'
#          - 'v6.5.0'
#          - 'v6.5.1'
#          - 'v6.5.2'
#          - 'v6.5.3'
#          - 'v6.5.4'

    name: Shopware ${{ matrix.shopware-version }}

    container:
      image: ghcr.io/friendsofshopware/platform-plugin-dev:${{ matrix.shopware-version }}-bullseye
    env:
      PLUGIN_DIR: /plugins/EasyCreditRatenkauf
      SW_DIR: /opt/shopware
      SW_VERSION: ${{ matrix.shopware-version }}
 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Debug
        run: |
          php -v
          php -m
          composer -V
          env
      - name: Start mysql server
        run: start-mysql
      - name: Link plugin with shopware installation and install composer deps
        run:  |
          ln -s $GITHUB_WORKSPACE $PLUGIN_DIR
          cd $PLUGIN_DIR
          composer remove shopware/core frosh/shopware-rector
          composer install -n
      - name: Static Analyze
        if: false
        run: |
          cd $PLUGIN_DIR
          php $PLUGIN_DIR/bin/phpstan-config-generator.php
          php $PLUGIN_DIR/vendor/bin/phpstan dump-parameters
          php $PLUGIN_DIR/vendor/bin/phpstan analyze $PLUGIN_DIR/src
      - name: Coding Style
        if: false
        run: |
          cd $PLUGIN_DIR
          php vendor/bin/ecs check --config=ecs.php
      - name: Install & activate Plugin
        run: |
          cd $SW_DIR
          php bin/console plugin:refresh
          php bin/console plugin:install EasyCreditRatenkauf
          php bin/console plugin:activate EasyCreditRatenkauf
          php bin/console system:config:set EasyCreditRatenkauf.config.webshopId ${{ secrets.EASYCREDITAPIKEY }}
          php bin/console system:config:set EasyCreditRatenkauf.config.apiPassword ${{ secrets.EASYCREDITAPIPASSWORD }}
          php bin/console system:config:set EasyCreditRatenkauf.config.apiSignature ${{ secrets.EASYCREDITAPISIGNATURE }}

          mysql -u root -proot shopware -e 'INSERT IGNORE INTO sales_channel_payment_method SELECT s.id, p.id FROM payment_method p INNER JOIN sales_channel s WHERE handler_identifier = "Netzkollektiv\\EasyCredit\\Payment\\Handler";'

          php bin/console cache:clear
      - name: Playwright E2E Tests
        run: |
          cd $SW_DIR
          ./bin/console sales-channel:create:storefront --url http://localhost
          ./bin/console theme:change --all -n Storefront
          #APP_ENV=prod php bin/console framework:demodata
          php bin/console dal:refresh:index -qn
          php bin/console user:create --admin --email=john@doe.com --firstName="John" --lastName="Doe" --password=shopware --no-interaction admin

          cd public
          php -S localhost:80 &

          cd $PLUGIN_DIR
          npm install --global yarn
          yarn install --frozen-lockfile
          yarn playwright install --with-deps
          VERSION=${{ matrix.shopware-version }} yarn playwright test -c tests/
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: test-results/
          retention-days: 30
      - name: Deactivate & uninstall Plugin
        run: |
          cd $SW_DIR
          php bin/console plugin:deactivate EasyCreditRatenkauf
          php bin/console plugin:uninstall EasyCreditRatenkauf
          php bin/console cache:clear
