name: Test

on:
  push:
    branches:
    - 'phpstan'

jobs:
  ci-current:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        shopware-version: ['v6.3.2', 'v6.4.1', 'v6.4.9', 'v6.4.10', 'v6.4.11', 'v6.4.12', 'v6.4.13', 'v6.4.14', 'v6.4.15', 'v6.4.16', 'v6.4.17', 'v6.4.18', 'v6.4.19', 'v6.4.20', 'v6.5.0' ]

    name: Shopware ${{ matrix.shopware-version }}

    container:
      image: ghcr.io/friendsofshopware/platform-plugin-dev:${{ matrix.shopware-version }}
    env:
      PLUGIN_DIR: /plugins/EasyCreditRatenkauf
      SW_DIR: /opt/shopware
      
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Debug
        run: |
          php -v
          php -m
          composer -V
          env
#      - name: Fix MySQL max_allowed_packet size
#        run: |
#          mysql -h db -u root -proot -e "SHOW VARIABLES LIKE 'max_allowed_packet'"
#          mysql -h db -u root -proot -e "SET GLOBAL max_allowed_packet = 99999999;"
#          mysql -h db -u root -proot -e "SHOW VARIABLES LIKE 'max_allowed_packet'"
      - name: Start mysql server
        run: start-mysql
      - name: Link plugin with shopware installation and install composer deps
        run:  |
          ln -s $GITHUB_WORKSPACE $PLUGIN_DIR
          cd $PLUGIN_DIR
          composer remove shopware/core
          composer install -n
      - name: Static Analyze
        run: |
          cd $PLUGIN_DIR
          php $PLUGIN_DIR/bin/phpstan-config-generator.php
          php $PLUGIN_DIR/vendor/bin/phpstan analyze $PLUGIN_DIR/src
      - name: Coding Style
        run: |
          cd $PLUGIN_DIR
          php vendor/bin/ecs check --config=ecs.php
      - name: Install & activate Plugin
        run: |
          cd $SW_DIR
          php bin/console plugin:refresh
          php bin/console plugin:install EasyCreditRatenkauf
          php bin/console plugin:activate EasyCreditRatenkauf
          php bin/console cache:clear

      - name: Deactivate & uninstall Plugin
        run: |
          cd $SW_DIR
          php bin/console plugin:deactivate EasyCreditRatenkauf
          php bin/console plugin:uninstall EasyCreditRatenkauf
          php bin/console cache:clear
