name: Test

on:
  push:
    branches:
    - 'phpstan'

jobs:
  ci-current:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        #php-version: [ '7.4', '8.0', '8.1' ]
        shopware-version: [ 'v6.4.20' ]

    name: Shopware ${{ matrix.shopware-version }}

    container:
      image: ghcr.io/friendsofshopware/platform-plugin-dev:${{ matrix.shopware-version }}
    env:
      PLUGIN_DIR: /plugins/EasyCreditRatenkauf
#      SW6SETUP_VERSION: ${{ matrix.shopware-version }}
#      SW6SETUP_URL: http://localhost

#    services:
#      db:
#        image: mysql:5.7.38
#        env:
#          MYSQL_ROOT_PASSWORD: root
#        ports:
#          - 3306:3306
#        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Debug
        run: |
          php -v
          php -m
          composer -V
#      - name: Fix MySQL max_allowed_packet size
#        run: |
#          mysql -h db -u root -proot -e "SHOW VARIABLES LIKE 'max_allowed_packet'"
#          mysql -h db -u root -proot -e "SET GLOBAL max_allowed_packet = 99999999;"
#          mysql -h db -u root -proot -e "SHOW VARIABLES LIKE 'max_allowed_packet'"
      - name: Start mysql
        run: start-mysql
      - name: Link plugin
        run:  |
          ln -s $GITHUB_WORKSPACE $PLUGIN_DIR
          cd $PLUGIN_DIR
          composer remove shopware/core
          composer install -n
#      - name: Composer setup
#        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --optimize-autoloader
#      - name: Install Shopware 6
#        run: ${PWD}/bin/setup.sh
#      - name: Install Plugin
#        run: ${PWD}/bin/install-plugin.sh
      - name: Static Analyze
        run: |
          php $PLUGIN_DIR/bin/phpstan-config-generator.php
          php $PLUGIN_DIR/vendor/bin/phpstan analyze $PLUGIN_DIR/src
